""" test case matrices Smith et al. 2012 """
from models.models import (
    CCMatrix, CCMatrixCell, CFMatrix, CFMatrixEntry,
    MCMatrix, MCMatrixCell, MFMatrix, MFMatrixEntry, PCMatrix, PCMatrixEntry
)

dg = [1, 2, 3, 4, 5, 6, 7, 8, 9, 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10']

cc_matrix2 = CCMatrix(num_components=9, num_directions=4)
cc_matrix2.data[0][0] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[0][1] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[0][2] = CCMatrixCell(components=[5], fasteners=['f1', 'f8'])
cc_matrix2.data[0][3] = CCMatrixCell(components=[2], fasteners=[])
cc_matrix2.data[1][0] = CCMatrixCell(components=[6], fasteners=[])
cc_matrix2.data[1][1] = CCMatrixCell(components=[], fasteners=['f2'])
cc_matrix2.data[1][2] = CCMatrixCell(components=[1], fasteners=['f1'])
cc_matrix2.data[1][3] = CCMatrixCell(components=[3], fasteners=['f3'])
cc_matrix2.data[2][0] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[2][1] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[2][2] = CCMatrixCell(components=[2, 4, 7], fasteners=[])
cc_matrix2.data[2][3] = CCMatrixCell(components=[], fasteners=['f3', 'f4', 'f5'])
cc_matrix2.data[3][0] = CCMatrixCell(components=[], fasteners=['f6', 'f7'])
cc_matrix2.data[3][1] = CCMatrixCell(components=[5, 8], fasteners=[])
cc_matrix2.data[3][2] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[3][3] = CCMatrixCell(components=[3], fasteners=['f5'])
cc_matrix2.data[4][0] = CCMatrixCell(components=[4], fasteners=['f7'])
cc_matrix2.data[4][1] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[4][2] = CCMatrixCell(components=[], fasteners=['f8'])
cc_matrix2.data[4][3] = CCMatrixCell(components=[1], fasteners=[])
cc_matrix2.data[5][0] = CCMatrixCell(components=[8], fasteners=[])
cc_matrix2.data[5][1] = CCMatrixCell(components=[2], fasteners=['f2', 'f10'])
cc_matrix2.data[5][2] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[5][3] = CCMatrixCell(components=[7], fasteners=['f4'])
cc_matrix2.data[6][0] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[6][1] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[6][2] = CCMatrixCell(components=[6, 9], fasteners=['f9'])
cc_matrix2.data[6][3] = CCMatrixCell(components=[3], fasteners=['f4'])
cc_matrix2.data[7][0] = CCMatrixCell(components=[4], fasteners=['f6'])
cc_matrix2.data[7][1] = CCMatrixCell(components=[6], fasteners=['f10'])
cc_matrix2.data[7][2] = CCMatrixCell(components=[], fasteners=['f9'])
cc_matrix2.data[7][3] = CCMatrixCell(components=[9], fasteners=[])
cc_matrix2.data[8][0] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[8][1] = CCMatrixCell(components=[], fasteners=[])
cc_matrix2.data[8][2] = CCMatrixCell(components=[8], fasteners=['f9'])
cc_matrix2.data[8][3] = CCMatrixCell(components=[7], fasteners=[])

cf_matrix2 = CFMatrix(data=[
    CFMatrixEntry(fastener='f1', direction=3),
    CFMatrixEntry(fastener='f2', direction=2),
    CFMatrixEntry(fastener='f3', direction=4),
    CFMatrixEntry(fastener='f4', direction=4),
    CFMatrixEntry(fastener='f5', direction=4),
    CFMatrixEntry(fastener='f6', direction=1),
    CFMatrixEntry(fastener='f7', direction=1),
    CFMatrixEntry(fastener='f8', direction=3),
    CFMatrixEntry(fastener='f9', direction=3),
    CFMatrixEntry(fastener='f10', direction=2),
])

mc_matrix2 = MCMatrix(num_components=9, num_directions=4)
mc_matrix2.data[0][0] = MCMatrixCell(components=[4], fasteners=['f1', 'f8'])
mc_matrix2.data[0][1] = MCMatrixCell(components=[], fasteners=['f1', 'f8'])
mc_matrix2.data[0][2] = MCMatrixCell(components=[], fasteners=[])
mc_matrix2.data[0][3] = MCMatrixCell(components=[6], fasteners=[])
mc_matrix2.data[1][0] = MCMatrixCell(components=[4, 7], fasteners=['f1', 'f3', 'f10'])
mc_matrix2.data[1][1] = MCMatrixCell(components=[], fasteners=['f1', 'f3'])
mc_matrix2.data[1][2] = MCMatrixCell(components=[], fasteners=['f2'])
mc_matrix2.data[1][3] = MCMatrixCell(components=[], fasteners=['f2'])
mc_matrix2.data[2][0] = MCMatrixCell(components=[], fasteners=['f3', 'f4', 'f5'])
mc_matrix2.data[2][1] = MCMatrixCell(components=[], fasteners=['f3', 'f4', 'f5'])
mc_matrix2.data[2][2] = MCMatrixCell(components=[6, 8], fasteners=[])
mc_matrix2.data[2][3] = MCMatrixCell(components=[], fasteners=[])
mc_matrix2.data[3][0] = MCMatrixCell(components=[], fasteners=['f5'])
mc_matrix2.data[3][1] = MCMatrixCell(components=[1, 2, 6, 7, 9], fasteners=['f5'])
mc_matrix2.data[3][2] = MCMatrixCell(components=[], fasteners=['f6', 'f7'])
mc_matrix2.data[3][3] = MCMatrixCell(components=[], fasteners=['f6', 'f7'])
mc_matrix2.data[4][0] = MCMatrixCell(components=[], fasteners=['f8'])
mc_matrix2.data[4][1] = MCMatrixCell(components=[], fasteners=['f8'])
mc_matrix2.data[4][2] = MCMatrixCell(components=[], fasteners=['f7'])
mc_matrix2.data[4][3] = MCMatrixCell(components=[8], fasteners=['f7', 'f9'])
mc_matrix2.data[5][0] = MCMatrixCell(components=[4, 9], fasteners=['f4'])
mc_matrix2.data[5][1] = MCMatrixCell(components=[], fasteners=['f4'])
mc_matrix2.data[5][2] = MCMatrixCell(components=[1], fasteners=['f2', 'f10'])
mc_matrix2.data[5][3] = MCMatrixCell(components=[3], fasteners=['f2', 'f10'])
mc_matrix2.data[6][0] = MCMatrixCell(components=[4], fasteners=['f4', 'f8'])
mc_matrix2.data[6][1] = MCMatrixCell(components=[2], fasteners=['f4', 'f8'])
mc_matrix2.data[6][2] = MCMatrixCell(components=[8], fasteners=[])
mc_matrix2.data[6][3] = MCMatrixCell(components=[], fasteners=[])
mc_matrix2.data[7][0] = MCMatrixCell(components=[], fasteners=['f9'])
mc_matrix2.data[7][1] = MCMatrixCell(components=[], fasteners=['f9'])
mc_matrix2.data[7][2] = MCMatrixCell(components=[5], fasteners=['f6', 'f10'])
mc_matrix2.data[7][3] = MCMatrixCell(components=[3, 7], fasteners=['f6', 'f10'])
mc_matrix2.data[8][0] = MCMatrixCell(components=[4], fasteners=['f9'])
mc_matrix2.data[8][1] = MCMatrixCell(components=[6], fasteners=['f9'])
mc_matrix2.data[8][2] = MCMatrixCell(components=[], fasteners=[])
mc_matrix2.data[8][3] = MCMatrixCell(components=[], fasteners=[])

mf_matrix2 = MFMatrix(num_fasteners=10, num_directions=4)
mf_matrix2.data[0][0] = MFMatrixEntry(component=None)
mf_matrix2.data[0][1] = MFMatrixEntry(component=None)
mf_matrix2.data[0][2] = MFMatrixEntry(component=None)
mf_matrix2.data[0][3] = MFMatrixEntry(component=None)
mf_matrix2.data[1][0] = MFMatrixEntry(component=None)
mf_matrix2.data[1][1] = MFMatrixEntry(component=None)
mf_matrix2.data[1][2] = MFMatrixEntry(component=None)
mf_matrix2.data[1][3] = MFMatrixEntry(component=None)
mf_matrix2.data[2][0] = MFMatrixEntry(component=None)
mf_matrix2.data[2][1] = MFMatrixEntry(component=None)
mf_matrix2.data[2][2] = MFMatrixEntry(component=None)
mf_matrix2.data[2][3] = MFMatrixEntry(component=None)
mf_matrix2.data[3][0] = MFMatrixEntry(component=None)
mf_matrix2.data[3][1] = MFMatrixEntry(component=None)
mf_matrix2.data[3][2] = MFMatrixEntry(component=None)
mf_matrix2.data[3][3] = MFMatrixEntry(component=None)
mf_matrix2.data[4][0] = MFMatrixEntry(component=None)
mf_matrix2.data[4][1] = MFMatrixEntry(component=None)
mf_matrix2.data[4][2] = MFMatrixEntry(component=None)
mf_matrix2.data[4][3] = MFMatrixEntry(component=None)
mf_matrix2.data[5][0] = MFMatrixEntry(component=None)
mf_matrix2.data[5][1] = MFMatrixEntry(component=None)
mf_matrix2.data[5][2] = MFMatrixEntry(component=None)
mf_matrix2.data[5][3] = MFMatrixEntry(component=None)
mf_matrix2.data[6][0] = MFMatrixEntry(component=None)
mf_matrix2.data[6][1] = MFMatrixEntry(component=None)
mf_matrix2.data[6][2] = MFMatrixEntry(component=None)
mf_matrix2.data[6][3] = MFMatrixEntry(component=None)
mf_matrix2.data[7][0] = MFMatrixEntry(component=None)
mf_matrix2.data[7][1] = MFMatrixEntry(component=None)
mf_matrix2.data[7][2] = MFMatrixEntry(component=None)
mf_matrix2.data[7][3] = MFMatrixEntry(component=None)
mf_matrix2.data[8][0] = MFMatrixEntry(component=None)
mf_matrix2.data[8][1] = MFMatrixEntry(component=None)
mf_matrix2.data[8][2] = MFMatrixEntry(component=5)
mf_matrix2.data[8][3] = MFMatrixEntry(component=None)
mf_matrix2.data[9][0] = MFMatrixEntry(component=None)
mf_matrix2.data[9][1] = MFMatrixEntry(component=2)
mf_matrix2.data[9][2] = MFMatrixEntry(component=None)
mf_matrix2.data[9][3] = MFMatrixEntry(component=None)

pc_matrix2 = PCMatrix(num_components=9, num_directions=4)
pc_matrix2.data[0][0] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[0][1] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[0][2] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[0][3] = PCMatrixEntry(blocking_components=4)
pc_matrix2.data[1][0] = PCMatrixEntry(blocking_components=5)
pc_matrix2.data[1][1] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[1][2] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[1][3] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[2][0] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[2][1] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[2][2] = PCMatrixEntry(blocking_components=8)
pc_matrix2.data[2][3] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[3][0] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[3][1] = PCMatrixEntry(blocking_components=7)
pc_matrix2.data[3][2] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[3][3] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[4][0] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[4][1] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[4][2] = PCMatrixEntry(blocking_components=0)
pc_matrix2.data[4][3] = PCMatrixEntry(blocking_components=6)
pc_matrix2.data[5][0] = PCMatrixEntry(blocking_components=3)
pc_matrix2.data[5][1] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[5][2] = PCMatrixEntry(blocking_components=2)
pc_matrix2.data[5][3] = PCMatrixEntry(blocking_components=2)
pc_matrix2.data[6][0] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[6][1] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[6][2] = PCMatrixEntry(blocking_components=5)
pc_matrix2.data[6][3] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[7][0] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[7][1] = PCMatrixEntry(blocking_components=2)
pc_matrix2.data[7][2] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[7][3] = PCMatrixEntry(blocking_components=3)
pc_matrix2.data[8][0] = PCMatrixEntry(blocking_components=1)
pc_matrix2.data[8][1] = PCMatrixEntry(blocking_components=2)
pc_matrix2.data[8][2] = PCMatrixEntry(blocking_components=2)
pc_matrix2.data[8][3] = PCMatrixEntry(blocking_components=2)
